CREATE TABLE IF NOT EXISTS route_assignments (
  id TEXT PRIMARY KEY,
  route_id TEXT NOT NULL,
  retainer_id TEXT NOT NULL,
  seeker_id TEXT NOT NULL,
  assignment_type TEXT NOT NULL,
  unit_type TEXT NOT NULL,
  cadence TEXT NOT NULL,
  expected_units_per_period INTEGER,
  start_date TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'ACTIVE',
  data_json TEXT,
  is_seed INTEGER NOT NULL DEFAULT 0,
  seed_batch_id TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (route_id) REFERENCES routes(id) ON DELETE CASCADE,
  FOREIGN KEY (retainer_id) REFERENCES retainers(id) ON DELETE CASCADE,
  FOREIGN KEY (seeker_id) REFERENCES seekers(id) ON DELETE CASCADE,
  FOREIGN KEY (seed_batch_id) REFERENCES seed_batches(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS work_unit_periods (
  id TEXT PRIMARY KEY,
  assignment_id TEXT NOT NULL,
  period_key TEXT NOT NULL,
  cadence TEXT NOT NULL,
  expected_units INTEGER,
  accepted_units INTEGER,
  completed_units INTEGER,
  missed_units INTEGER,
  status TEXT NOT NULL DEFAULT 'PENDING',
  seeker_response TEXT NOT NULL DEFAULT 'NONE',
  admin_resolution TEXT NOT NULL DEFAULT 'NONE',
  dispute_note TEXT,
  admin_note TEXT,
  retainer_submitted_at TEXT,
  seeker_responded_at TEXT,
  window_closes_at TEXT,
  data_json TEXT,
  is_seed INTEGER NOT NULL DEFAULT 0,
  seed_batch_id TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (assignment_id) REFERENCES route_assignments(id) ON DELETE CASCADE,
  FOREIGN KEY (seed_batch_id) REFERENCES seed_batches(id) ON DELETE SET NULL
);
